



#' Find significance of bipartite network with customized null model
#'
#' @param inputName_modularity name of a csv file saving real modularity Q.
#' @param inputName_incidmat name of a csv file saving incidence matrix.
#' @param signif_preserve null models to use on incidence matrix. 'density' shuffles entries across whole matrix, 'row_deg' shuffles entries within each row, 'col_deg' shuffles entries within each column.
#' @param signif_N_sample number of random networks generated for significance test. Must be greater than 2.
#' @param outputName_Qrandomdist name of a csv file to save modularity and number of clusters for each randomly generated network
#' @param outputName_zp_Q name of a csv file to save significance result including z-score, p-value and other information.
#'
#' @return significance result including z-score, p-value and other information.
#'
#'
#' This function does the following things:
#' 1. reads bipartite network data represented as incidence matrix from [inputName_incidmat];
#' 2. reads real modularity from [inputName_modularity];
#' 3. finds significance of modularity using specific null model, saves the modularity distribution of the random networks generated by the null model to [outputName_Qrandomdist], and saves the significance result to [outputName_zp_Q];
#'
#' @export
utility_ModSig = function(inputName_modularity = 'example_modularity.csv' ,
                          inputName_incidmat = 'example_incidmat.csv',
                          signif_preserve = 'col_deg',
                          signif_N_sample = 10,
                          outputName_Qrandomdist = 'example_Qrandomdist.csv',
                          outputName_zp_Q = 'example_zp_Q.csv') {
  print('Read incidence matrix.')
  incid_mat = utils::read.csv(inputName_incidmat, row.names = 1) # Read incidence matrix.
  utils::str(incid_mat)

  print('Read modularity.')
  Q_real = utils::read.csv(inputName_modularity)$Q # Read modularity.
  utils::str(Q_real)

  if (signif_N_sample >= 3) {
    print(
      'Get significance of real modularity compared to modularity distribution of random networks with user specified null model.'
    )
    Q_randomdist = simulate_modularity_distribution_for_null_model(incid_mat, N_sample = signif_N_sample, preserve = signif_preserve)
    utils::write.csv(Q_randomdist,
                     outputName_Qrandomdist,
                     row.names = F)
    zp = get_significance_zp(Q_real, Q_randomdist$Q)
    utils::write.csv(zp, outputName_zp_Q, row.names = F)
  } else {
    stop('signif_N_sample must be greater than 2.')
  }
  return(zp)
}
